version: '3.4'

services:
  messagebatching:
    image: ${DOCKER_REGISTRY-}messagebatching
    build:
      context: .
      dockerfile: MessageBatching/Dockerfile
  queueconsumer:
    image: ${DOCKER_REGISTRY-}messagebatching
    build: 
        context: .
        dockerfile: QueueConsumer/Dockerfile
  rabbitmq:
     image: rabbitmq:3-management-alpine
     container_name: 'rabbitmq'
     ports:
        - 5672:5672
        - 15672:15672