version: '3.4'

services:
  messagebatching:
    image: messagebatching:dev
    container_name: MessageBatching_1
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "QueueProducer"
    environment:
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Development\QueueMsgBatching\MessageBatching\MessageBatching:/app
      - C:\Users\e-sndu\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\e-sndu\.nuget\packages\:/root/.nuget/packages:ro
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/QueueProducer.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  queueconsumer:
    image: messagebatching:dev
    container_name: QueueConsumer
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "QueueConsumer"
    environment:
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Development\QueueMsgBatching\MessageBatching\QueueConsumer:/app
      - C:\Users\e-sndu\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\e-sndu\.nuget\packages\:/root/.nuget/packages:ro
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/QueueConsumer.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
